### ISSUE TITLE
UAS and ULS to XJUS?

### ISSUE THREAD

**Issue by kli017** [neouyghur/Uyghur-Multi-Script-Converter#8]
Hello, I want convert uas and uls to xjus, is it possilble?

**Comment by neouyghur** [comment]
Yes, it is possible. Please use these acronyms. 


ULS | Uyghur Latin Script
UYS | Uyghur Yengi (New) Script
CPS | Chinese Pinyin Script
UAS | Uyghur Arabic Script
CTS |Common Turkic Script
UCS | Uyghur Cyrillic Script
XJU | Xinjinag University English Case Sensitive
UZBEK | Uzbek

```
from umsc import UgMultiScriptConverter
source_script = 'UAS'
target_script = 'XJU'
converter = UgMultiScriptConverter(source_script, target_script)
text = 'ياخشىمۇسىز!'
text = converter(text)
print(text)
```
